// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbgo.proto

package pbgo // import "github.com/chai2010/pbgo"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RestMethodOption struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Get                  string   `protobuf:"bytes,3,opt,name=get,proto3" json:"get,omitempty"`
	Post                 string   `protobuf:"bytes,4,opt,name=post,proto3" json:"post,omitempty"`
	Put                  string   `protobuf:"bytes,5,opt,name=put,proto3" json:"put,omitempty"`
	Patch                string   `protobuf:"bytes,6,opt,name=patch,proto3" json:"patch,omitempty"`
	Delete               string   `protobuf:"bytes,7,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestMethodOption) Reset()         { *m = RestMethodOption{} }
func (m *RestMethodOption) String() string { return proto.CompactTextString(m) }
func (*RestMethodOption) ProtoMessage()    {}
func (*RestMethodOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbgo_a4d9b20332b0f9ad, []int{0}
}
func (m *RestMethodOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestMethodOption.Unmarshal(m, b)
}
func (m *RestMethodOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestMethodOption.Marshal(b, m, deterministic)
}
func (dst *RestMethodOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestMethodOption.Merge(dst, src)
}
func (m *RestMethodOption) XXX_Size() int {
	return xxx_messageInfo_RestMethodOption.Size(m)
}
func (m *RestMethodOption) XXX_DiscardUnknown() {
	xxx_messageInfo_RestMethodOption.DiscardUnknown(m)
}

var xxx_messageInfo_RestMethodOption proto.InternalMessageInfo

func (m *RestMethodOption) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RestMethodOption) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RestMethodOption) GetGet() string {
	if m != nil {
		return m.Get
	}
	return ""
}

func (m *RestMethodOption) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

func (m *RestMethodOption) GetPut() string {
	if m != nil {
		return m.Put
	}
	return ""
}

func (m *RestMethodOption) GetPatch() string {
	if m != nil {
		return m.Patch
	}
	return ""
}

func (m *RestMethodOption) GetDelete() string {
	if m != nil {
		return m.Delete
	}
	return ""
}

var E_RestMethodOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*RestMethodOption)(nil),
	Field:         20180715,
	Name:          "pbgo.rest_method_option",
	Tag:           "bytes,20180715,opt,name=rest_method_option,json=restMethodOption",
	Filename:      "pbgo.proto",
}

func init() {
	proto.RegisterType((*RestMethodOption)(nil), "pbgo.RestMethodOption")
	proto.RegisterExtension(E_RestMethodOption)
}

func init() { proto.RegisterFile("pbgo.proto", fileDescriptor_pbgo_a4d9b20332b0f9ad) }

var fileDescriptor_pbgo_a4d9b20332b0f9ad = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0xa9, 0xd3, 0xa9, 0x4c, 0xdc, 0x94, 0x20, 0x43, 0x10, 0xd4, 0xe2, 0x6a, 0x56, 0xe9,
	0x38, 0xee, 0x74, 0xe7, 0x5e, 0x84, 0x2e, 0xdd, 0x0c, 0xd3, 0xf6, 0x99, 0x16, 0x3a, 0xbe, 0x90,
	0xbc, 0xfc, 0x90, 0x3f, 0xe4, 0x17, 0xf8, 0x05, 0xfe, 0x84, 0x24, 0x4f, 0x61, 0xe8, 0xa6, 0xdc,
	0x7b, 0xb8, 0xe5, 0xbe, 0x1b, 0x21, 0x6c, 0x6b, 0x50, 0x5b, 0x87, 0x84, 0x32, 0x8f, 0xfa, 0xaa,
	0x32, 0x88, 0x66, 0x82, 0x3a, 0xb1, 0x36, 0xbc, 0xd7, 0x3d, 0xf8, 0xce, 0x8d, 0x96, 0xd0, 0x71,
	0xee, 0xee, 0x33, 0x13, 0x65, 0x03, 0x9e, 0x5e, 0x80, 0x06, 0xec, 0x5f, 0x2d, 0x8d, 0xf8, 0x21,
	0xd7, 0xa2, 0x38, 0x26, 0xaf, 0xb2, 0x2a, 0xdb, 0xac, 0x9a, 0x3f, 0x27, 0x4b, 0xb1, 0x08, 0x6e,
	0x52, 0x67, 0x09, 0x46, 0x19, 0x89, 0x01, 0x52, 0x0b, 0x26, 0x06, 0x48, 0x4a, 0x91, 0x5b, 0xf4,
	0xa4, 0xf2, 0x84, 0x92, 0x8e, 0x29, 0x1b, 0x48, 0x2d, 0x39, 0x65, 0x03, 0xc9, 0x4b, 0xb1, 0xb4,
	0x07, 0xea, 0x06, 0x55, 0x24, 0xc6, 0x26, 0xf6, 0xf6, 0x30, 0x01, 0x81, 0x3a, 0xe7, 0x5e, 0x76,
	0x8f, 0x46, 0x48, 0x07, 0x9e, 0xf6, 0x7c, 0xc6, 0x1e, 0xf9, 0xca, 0x1b, 0xcd, 0xeb, 0xf4, 0xff,
	0x3a, 0x7d, 0x3a, 0xc2, 0xab, 0x9f, 0xef, 0xaf, 0x55, 0x95, 0x6d, 0x2e, 0x76, 0x6b, 0x9d, 0x1e,
	0x66, 0x3e, 0xb3, 0x29, 0xdd, 0x8c, 0x3c, 0xdf, 0xbe, 0x5d, 0x9b, 0x91, 0x86, 0xd0, 0xea, 0x0e,
	0x8f, 0x75, 0x37, 0x1c, 0xc6, 0xdd, 0xf6, 0x7e, 0x5b, 0xc7, 0xdf, 0x9f, 0xe2, 0xa7, 0x2d, 0x52,
	0xd7, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x82, 0x76, 0xe6, 0x6b, 0x01, 0x00, 0x00,
}
