// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbgo.proto

package pbgo // import "github.com/chai2010/pbgo"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RestMethodOption struct {
	Method               string              `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string              `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	AdditionalBindings   []*RestMethodOption `protobuf:"bytes,3,rep,name=additional_bindings,json=additionalBindings,proto3" json:"additional_bindings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RestMethodOption) Reset()         { *m = RestMethodOption{} }
func (m *RestMethodOption) String() string { return proto.CompactTextString(m) }
func (*RestMethodOption) ProtoMessage()    {}
func (*RestMethodOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbgo_41fbb482fde90d77, []int{0}
}
func (m *RestMethodOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestMethodOption.Unmarshal(m, b)
}
func (m *RestMethodOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestMethodOption.Marshal(b, m, deterministic)
}
func (dst *RestMethodOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestMethodOption.Merge(dst, src)
}
func (m *RestMethodOption) XXX_Size() int {
	return xxx_messageInfo_RestMethodOption.Size(m)
}
func (m *RestMethodOption) XXX_DiscardUnknown() {
	xxx_messageInfo_RestMethodOption.DiscardUnknown(m)
}

var xxx_messageInfo_RestMethodOption proto.InternalMessageInfo

func (m *RestMethodOption) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RestMethodOption) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RestMethodOption) GetAdditionalBindings() []*RestMethodOption {
	if m != nil {
		return m.AdditionalBindings
	}
	return nil
}

var E_RestMethodOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*RestMethodOption)(nil),
	Field:         20180715,
	Name:          "pbgo.rest_method_option",
	Tag:           "bytes,20180715,opt,name=rest_method_option,json=restMethodOption",
	Filename:      "pbgo.proto",
}

func init() {
	proto.RegisterType((*RestMethodOption)(nil), "pbgo.RestMethodOption")
	proto.RegisterExtension(E_RestMethodOption)
}

func init() { proto.RegisterFile("pbgo.proto", fileDescriptor_pbgo_41fbb482fde90d77) }

var fileDescriptor_pbgo_41fbb482fde90d77 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x48, 0x4a, 0xcf,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x14, 0xd2, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0xc1, 0x62, 0x49, 0xa5, 0x69, 0xfa, 0x29, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05,
	0x25, 0xf9, 0x45, 0x10, 0x75, 0x4a, 0xad, 0x8c, 0x5c, 0x02, 0x41, 0xa9, 0xc5, 0x25, 0xbe, 0xa9,
	0x25, 0x19, 0xf9, 0x29, 0xfe, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x42, 0x62, 0x5c, 0x6c, 0xb9, 0x60,
	0xbe, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0x27, 0x24, 0xc0, 0xc5, 0x5c, 0x5a, 0x94,
	0x23, 0xc1, 0x04, 0x16, 0x04, 0x31, 0x85, 0xdc, 0xb9, 0x84, 0x13, 0x53, 0x52, 0x32, 0x41, 0xba,
	0x12, 0x73, 0xe2, 0x93, 0x32, 0xf3, 0x52, 0x32, 0xf3, 0xd2, 0x8b, 0x25, 0x98, 0x15, 0x98, 0x35,
	0xb8, 0x8d, 0xc4, 0xf4, 0xc0, 0x0e, 0x42, 0x37, 0x3e, 0x48, 0x08, 0xa1, 0xc5, 0x09, 0xaa, 0xc3,
	0x2a, 0x9d, 0x4b, 0xa8, 0x28, 0xb5, 0xb8, 0x24, 0x1e, 0x62, 0x53, 0x7c, 0x3e, 0xc4, 0x21, 0x72,
	0x7a, 0x10, 0x0f, 0xe8, 0xc1, 0x3c, 0xa0, 0x87, 0x6c, 0x50, 0xb1, 0xc4, 0xeb, 0xbb, 0xe7, 0x39,
	0x15, 0x18, 0xf1, 0x58, 0x25, 0x50, 0x84, 0x26, 0xe2, 0x24, 0x1f, 0x25, 0x9b, 0x9e, 0x59, 0x92,
	0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9c, 0x91, 0x98, 0x69, 0x64, 0x60, 0x68, 0xa0,
	0x0f, 0xd2, 0x6e, 0x0d, 0x22, 0x92, 0xd8, 0xc0, 0x76, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x8f, 0xa1, 0x4f, 0x5d, 0x4e, 0x01, 0x00, 0x00,
}
