// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbgo.proto

package pbgo // import "github.com/chai2010/pbgo"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RestMethodOption struct {
	Url                  *string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	HttpMethod           *string  `protobuf:"bytes,1,opt,name=http_method,json=httpMethod,def=GET" json:"http_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestMethodOption) Reset()         { *m = RestMethodOption{} }
func (m *RestMethodOption) String() string { return proto.CompactTextString(m) }
func (*RestMethodOption) ProtoMessage()    {}
func (*RestMethodOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbgo_b91ec48a0d528ab7, []int{0}
}
func (m *RestMethodOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestMethodOption.Unmarshal(m, b)
}
func (m *RestMethodOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestMethodOption.Marshal(b, m, deterministic)
}
func (dst *RestMethodOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestMethodOption.Merge(dst, src)
}
func (m *RestMethodOption) XXX_Size() int {
	return xxx_messageInfo_RestMethodOption.Size(m)
}
func (m *RestMethodOption) XXX_DiscardUnknown() {
	xxx_messageInfo_RestMethodOption.DiscardUnknown(m)
}

var xxx_messageInfo_RestMethodOption proto.InternalMessageInfo

const Default_RestMethodOption_HttpMethod string = "GET"

func (m *RestMethodOption) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *RestMethodOption) GetHttpMethod() string {
	if m != nil && m.HttpMethod != nil {
		return *m.HttpMethod
	}
	return Default_RestMethodOption_HttpMethod
}

var E_RestMethodOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*RestMethodOption)(nil),
	Field:         20180715,
	Name:          "github.com.chai2010.pbgo.rest_method_option",
	Tag:           "bytes,20180715,opt,name=rest_method_option,json=restMethodOption",
	Filename:      "pbgo.proto",
}

func init() {
	proto.RegisterType((*RestMethodOption)(nil), "github.com.chai2010.pbgo.RestMethodOption")
	proto.RegisterExtension(E_RestMethodOption)
}

func init() { proto.RegisterFile("pbgo.proto", fileDescriptor_pbgo_b91ec48a0d528ab7) }

var fileDescriptor_pbgo_b91ec48a0d528ab7 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x48, 0x4a, 0xcf,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b,
	0xce, 0xcf, 0xd5, 0x4b, 0xce, 0x48, 0xcc, 0x34, 0x32, 0x30, 0x34, 0xd0, 0x03, 0xc9, 0x4b, 0x29,
	0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0xd5, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xa4, 0x16,
	0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0xf4, 0x2a, 0x79, 0x71, 0x09, 0x04, 0xa5, 0x16,
	0x97, 0xf8, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0xf8, 0x17, 0x94, 0x64, 0xe6, 0xe7, 0x09, 0x09, 0x70,
	0x31, 0x97, 0x16, 0xe5, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x2a, 0x5c,
	0xdc, 0x19, 0x25, 0x25, 0x05, 0xf1, 0xb9, 0x60, 0x65, 0x12, 0x8c, 0x20, 0x19, 0x2b, 0x66, 0x77,
	0xd7, 0x90, 0x20, 0x2e, 0x90, 0x38, 0x44, 0xb7, 0x55, 0x35, 0x97, 0x50, 0x51, 0x6a, 0x71, 0x09,
	0x54, 0x55, 0x7c, 0x3e, 0xc4, 0x34, 0x39, 0x3d, 0x88, 0x23, 0xf4, 0x60, 0x8e, 0xd0, 0x43, 0xb6,
	0xac, 0x58, 0xe2, 0xf5, 0xdd, 0xf3, 0x9c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x5a, 0x7a, 0xb8, 0xfc,
	0xa1, 0x87, 0xee, 0xc4, 0x20, 0x81, 0x22, 0x34, 0x11, 0x27, 0xf9, 0x28, 0x59, 0x84, 0x76, 0x7d,
	0x98, 0x76, 0x7d, 0x90, 0x76, 0x6b, 0x10, 0x01, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xfb, 0x35,
	0x45, 0x32, 0x01, 0x00, 0x00,
}
