// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.proto

package form_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Comment struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Next                 string   `protobuf:"bytes,5,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Comment) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Comment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Comment) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func init() {
	proto.RegisterType((*Comment)(nil), "form_pb.Comment")
}

func init() {
	proto.RegisterFile("comment.proto", fileDescriptor_749aee09ea917828)
}

var fileDescriptor_749aee09ea917828 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xcb, 0x2f, 0xca, 0x8d,
	0x2f, 0x48, 0x52, 0xca, 0xe5, 0x62, 0x77, 0x86, 0xc8, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x16, 0xa7,
	0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9, 0xb9,
	0x89, 0x99, 0x39, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0x48, 0x80, 0x8b, 0xb9, 0xb4, 0x28, 0x47,
	0x82, 0x19, 0x2c, 0x06, 0x62, 0x82, 0xf4, 0x96, 0xa4, 0x56, 0x94, 0x48, 0xb0, 0x40, 0xf4, 0x82,
	0xd8, 0x20, 0xb1, 0x3c, 0x90, 0x18, 0x2b, 0x44, 0x0c, 0xc4, 0x4e, 0x62, 0x03, 0x5b, 0x6f, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x76, 0x0a, 0x4d, 0x17, 0x8f, 0x00, 0x00, 0x00,
}
